version = 0.1
[default.deploy.parameters]
stack_name = "george-cloud-resume"
resolve_s3 = true
s3_prefix = "george-cloud-resume"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
